name: CI
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install dependencies
        run: |
          uv sync --locked --extra signing --python ${{ matrix.python-version }}

      - name: Style Check
        run: |
          uv run black --check tests/*
          uv run black --check wacz/*

      - name: Test with pytest
        run: |
          set -e
          uv run pytest --cov-config=.coveragerc
          uv run pytest -v --cov=wacz --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          verbose: true  
